# Generated by Django 3.0.8 on 2020-07-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, unique=True, verbose_name='Headline')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='Modified at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
